# Generated by Django 3.0 on 2020-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budjetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
