# Generated by Django 3.0 on 2020-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budjetapp', '0002_auto_20201224_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('exp_image', models.FileField(null=True, upload_to='experts/')),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
