# Generated by Django 3.0 on 2020-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budjetapp', '0004_consults'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
