# Generated by Django 3.0 on 2020-12-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budjetapp', '0009_auto_20201226_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphs',
            name='value',
            field=models.CharField(auto_created=True, max_length=30),
        ),
    ]
